create table if not exists public.courses (
  id bigint generated by default as identity primary key,
  course_name text not null,
  course_code text not null unique,
  instructor text not null,
  duration text not null,
  level text not null,
  category text not null,
  image text not null default '',
  status text not null default 'Active',
  overview text not null default '',
  description text not null default '',
  learning_outcomes jsonb not null default '[]'::jsonb,
  modules jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.courses enable row level security;

drop policy if exists "Courses are viewable by everyone" on public.courses;
create policy "Courses are viewable by everyone"
  on public.courses for select
  using (true);

drop policy if exists "Signed-in users can add courses" on public.courses;
drop policy if exists "Admins can add courses" on public.courses;
create policy "Admins can add courses"
  on public.courses for insert to authenticated
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Signed-in users can update courses" on public.courses;
drop policy if exists "Admins can update courses" on public.courses;
create policy "Admins can update courses"
  on public.courses for update to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin')
  with check ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

drop policy if exists "Signed-in users can delete courses" on public.courses;
drop policy if exists "Admins can delete courses" on public.courses;
create policy "Admins can delete courses"
  on public.courses for delete to authenticated
  using ((auth.jwt() -> 'app_metadata' ->> 'role') = 'admin');

insert into public.courses (
  course_name, course_code, instructor, duration, level, category, image,
  status, overview, description, learning_outcomes, modules
) values
  (
    'Python Programming', 'CS101', 'Dr. Anu', '8 Weeks', 'Beginner', 'Programming',
    'https://cdn-icons-png.flaticon.com/512/5968/5968350.png', 'Active',
    'Learn Python programming from beginner to advanced level.',
    'A practical introduction to Python with problem solving, functions and object-oriented programming.',
    '["Understand Python basics", "Work with functions", "Use object-oriented programming", "Build Python applications"]'::jsonb,
    '["Python Basics", "Control Statements", "Functions", "OOP", "Mini Project"]'::jsonb
  ),
  (
    'Web Development', 'WD101', 'Dr. Priya', '10 Weeks', 'Intermediate', 'Web Development',
    'https://cdn-icons-png.flaticon.com/512/1006/1006363.png', 'Active',
    'Learn HTML, CSS and JavaScript for modern web development.',
    'Build responsive interfaces and understand browser-side development and REST API integration.',
    '["Create semantic HTML", "Design responsive websites", "Use JavaScript", "Work with APIs"]'::jsonb,
    '["HTML", "CSS", "JavaScript", "DOM", "REST APIs"]'::jsonb
  ),
  (
    'Artificial Intelligence', 'AI101', 'Dr. Priya', '12 Weeks', 'Advanced', 'Artificial Intelligence',
    'https://cdn-icons-png.flaticon.com/512/4712/4712027.png', 'Active',
    'Learn the fundamentals of Artificial Intelligence.',
    'Explore machine learning, neural networks and practical AI application development.',
    '["Understand AI concepts", "Explore machine learning", "Understand neural networks", "Build AI applications"]'::jsonb,
    '["Introduction to AI", "Machine Learning", "Neural Networks", "Generative AI", "AI Project"]'::jsonb
  ),
  (
    'Data Structures', 'CS201', 'Dr. Priya', '10 Weeks', 'Intermediate', 'Programming',
    '', 'Active',
    'Master arrays, linked lists, stacks, queues, trees and algorithmic thinking.',
    'A practical DSA course designed around implementation, problem solving and complexity analysis.',
    '["Implement core data structures", "Analyze time complexity", "Solve algorithmic problems", "Apply DSA patterns"]'::jsonb,
    '["Arrays", "Linked Lists", "Stacks & Queues", "Trees", "Algorithms"]'::jsonb
  )
on conflict (course_code) do nothing;

create table if not exists public.enrollments (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  course_id bigint not null references public.courses(id) on delete cascade,
  status text not null default 'Enrolled',
  progress integer not null default 0 check (progress between 0 and 100),
  created_at timestamptz not null default now(),
  unique (user_id, course_id)
);

alter table public.enrollments enable row level security;

drop policy if exists "Users can view their own enrollments" on public.enrollments;
create policy "Users can view their own enrollments"
  on public.enrollments for select to authenticated
  using (user_id = auth.uid());

drop policy if exists "Users can enroll themselves" on public.enrollments;
create policy "Users can enroll themselves"
  on public.enrollments for insert to authenticated
  with check (user_id = auth.uid());

drop policy if exists "Users can update their own enrollments" on public.enrollments;
create policy "Users can update their own enrollments"
  on public.enrollments for update to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());

drop policy if exists "Users can delete their own enrollments" on public.enrollments;
create policy "Users can delete their own enrollments"
  on public.enrollments for delete to authenticated
  using (user_id = auth.uid());